brave/brave-talk

src/index.ts
=> Get rid of "call" column

.github/workflows/deploy-to-development-premium.yml, .github/workflows/deploy-to-production-premium.yml, .github/workflows/deploy-to-staging-premium.yml, package-lock.json, package.json, src/subscriptions.ts
And while I was in the area:
- make the logging in subscriptions a bit less repetative
- remove the config of a private access token in the github actions (not needed as @brave-intl/skus-sdk is public)
- improve consistency between the github actions
=> Update the skus-sdk to the publicly released version

src/subscriptions.ts
See https://github.com/brave/brave-talk/pull/71#discussion_r761326423
=> Check "active" value on skus-sdk

src/index.ts, src/subscriptions.ts
=> Production release: fix fetching credentials for newly created orders

src/index.ts, src/rules.test.ts, src/rules.ts
=> Messaging for free call room count & opt-in relaxation

src/index.ts
=> Disable before unload handlers

.github/actions/build/action.yml, .github/actions/deploy/action.yml, .github/workflows/check.yml, .github/workflows/deploy-to-development-premium.yml, .github/workflows/deploy-to-production-premium.yml, .github/workflows/deploy-to-staging-premium.yml
- reduce the copy-paste between scripts (though sadly the verbosity of composite actions mean this doesn't actually reduce file size at all - the opposite in fact - but the commonality of script is worth it I think)
- run build, unit-test and audit on every push
Re #104
=> CI Improvements

.github/actions/build/action.yml, .github/actions/deploy/action.yml, .github/workflows/check.yml, .github/workflows/codeql-analysis.yml, .github/workflows/deploy-to-development-premium.yml, .github/workflows/deploy-to-production-premium.yml, .github/workflows/deploy-to-staging-premium.yml, src/index.ts
- #102 
- #103 
- #108 
The only change here to the deployed code is removing the manually maintained version number from the startup console.log. The aim of this release is primarily to validate the changes made to the release scripts themselves.
=> Production Release

package-lock.json, package.json
"Works on dev". Please sanity check prior to approval and deploy.
=> Update to latest dependabot PRs

src/index.ts
=> Add logging around subject change logic

.github/actions/deploy/action.yml, src/index.ts
=> Production Release: fully clear cloudfront on deploy 

package-lock.json, src/css/welcome.css, src/general-store.ts, src/index.html, src/index.ts
=> Basic talk extension promo box

src/jwt-store.test.ts, src/jwt-store.ts
=> Production Release: Re-enable refresh token expiration

package-lock.json, package.json
=> Res ipsa loquitur

src/index.ts
Testing this was a bit difficult, because a change in the aspect ratio impacts what you see (and it looked OK with earlier testing). Fortunately, i tested again after changing the window ratio, and saw the issue re-emerge, so it could be diagnosed... _Sigh_
=> Disable tile enlargement should be true

package-lock.json, package.json
Update to the very latest requested by `dependabot`.
=> Dependabot updates 2022-04-11

package-lock.json, package.json
=> Rollup of dependabot updates as of 2022-04-22

package-lock.json, package.json
=> Dependabot updates 2022-05-09

package-lock.json, package.json
=> Merge dependabot updates from 2022-05-09

src/general-store.ts
extension pop-up counter function added in general-store.ts
=> counter for extension pop-up

src/css/welcome.css, src/index.html
`noscript` tag added for JS-disabled.
=> JS-disabled

package-lock.json, package.json
=> Dependabot updates as of 2022-05-31

package-lock.json, package.json
=> dependabot rollup

package-lock.json, package.json
looks fine on the developer server.
=> dependabot updates as of 2022-06-13

package-lock.json, package.json
=> Dependabot updates as of 2022-07-04

package-lock.json, package.json
Looks good locally and on `dev`
=> dependabot updates as of 2022-07-06

package-lock.json, package.json
Rolls up all the dependabot updates, including the `terser` update.
=> Dependabot updates as of 2022-07-18

src/index.ts
we don't collect the stats, so generating the stats serves no purpose.
=> remove faceLandmarks

src/index.ts
=> Remove face landmarks

src/index.ts
Should avoid the intermittent issue with the subject not being set to "Brave Talk".
=> Set `localSubject` in config

package-lock.json, package.json
=> dependabot updates as of 2022-08-01

package-lock.json, package.json
=> dependabot updates as of 2022-08-15

src/locales/en/translation.json, src/locales/jp/translation.json
translation for this: "Oops! We were unable to connect to your meeting room. Please try again.";
=> added one more translation

src/index.ts
=> remove `'dial-in'` from `SHARING_FEATURES`

public/branding-config-dev.json, public/branding-config-staging.json
If approved, please *do not merge*.
=> Disable dial-in

src/locales/en/translation.json, src/locales/jp/translation.json, src/rules.test.ts, src/rules.ts
Tested on `dev` with iOS 16 ... thank you @stephendonner
=> Lockdown mode message

public/branding-config-dev.json, public/branding-config.json
=> Switch to black background

package-lock.json, package.json
looks good on laptop and on `dev`...
=> dependabot updates as of 2022-09-20

package-lock.json, package.json
=> Update to SKUs SDK 0.1.2

src/index.ts, src/rules.test.ts, src/rules.ts
=> remove dead code

package-lock.json, package.json
Looks good on the laptop and on `dev`
=> dependabot updates as of 2022-10-10

src/css/welcome.css, src/index.html, src/index.ts, src/rules.test.ts, src/rules.ts
=> More dead code removal

package-lock.json, package.json
=> dependabot updates as of 2022-10-24

package-lock.json, package.json
looks good on desktop, and on dev, and approved by QA!
=> dependabot updates as of 2022-11-01

src/index.ts
=> set timeout to 1 hour

src/index.ts
new API call `getNumberOfParticipants`
=> Inactivity timer part deux

src/index.ts
=> new API call... `getNumberOfParticipants`

package-lock.json, package.json
Looks good on desktop and `dev`
=> dependabot updates as of 2022-11-09

src/index.ts, src/jwt-store.ts
=> Use backtick syntax when appropriate

package-lock.json, package.json
=> Dependabot updates as of 2023 01 05

src/index.ts
allow `notice` to generate notifications during a conference
=> Allow notify messages after joining

package-lock.json, package.json
=> Dependabot updates as of 2023-02-24

src/index.ts
until pre-production issues are resolved.
=> delete the giphy proxy

src/index.html, src/index.tsx
Dynamically set external api JS based on tenant ID
=> Use different link for external api JS

package-lock.json, package.json
Looks good on desktop and `dev`
=> dependabot updates as of 2023-04-03

package-lock.json, package.json
=> the very latest!

.github/actions/build/action.yml, package-lock.json
=> Use an extended re for eval checking

src/rooms.ts
looks good on desktop and `dev`
=> normalize use of `console.warn`

.github/actions/build/action.yml
Looks good on desktop and `dev`
=> Use an extended RE to avoid false positives!

src/components/web3/api.ts
This reverts commit e1d998f82aaa2a687a8814453bc898917b595c0e.
=> Revert "Use subscriptions directly for simplehash proxy"

src/components/WelcomeScreen.tsx, src/components/web3/JoinCall.tsx, src/components/web3/OptionalSettings.tsx, src/components/web3/SelectableImageList.tsx, src/components/web3/StartCall.tsx, src/components/web3/Web3CTA.tsx, src/components/web3/api.ts, src/components/web3/core.ts, src/hooks/use-web3-call-state.ts, src/types.d.ts
Resolves the following issues from #818 : 1, 2, 4, 5, 6, 9
=> Web3 Bug Fixes

src/components/web3/PermissionTypeSelector.tsx
Which looks less ugly than a native drop down, and involves one less click.
https://user-images.githubusercontent.com/51444/233692943-3f6dee60-a769-4964-9723-52a3fb5d2010.mov
=> Use buttons to select call permission type

src/components/web3/Login.tsx, src/hooks/use-web3-call-state.ts
=> Web3 on reactify

package-lock.json, package.json, src/rooms.ts
- Fix for #823 
- Fix for #832 
- Fix for `yaml` vulnerability: https://github.com/advisories/GHSA-f9xv-q969-pqx4
- Fix for #850
=> Merge Fixes & Dependency Updates

package-lock.json, package.json, src/components/Background.tsx, src/components/web3/EIP4361.ts, src/components/web3/Login.tsx, src/hooks/use-web3-call-state.ts
- Fix background zooming when expanding optional selections
- Revert to using poap event ids instead of token ids
- Fix bug where participants in nft collection auth were set as moderators
=> Web3 Fixes

package-lock.json, package.json
=> dependabot updates as of 2023-05-08

src/components/WelcomeScreen.tsx
This reverts commit a5728ca7efd2da4d28a4f17b9c8a59ca78f1b492.
=> Revert "Add web3 gating w/ query param"

src/hooks/use-web3-call-state.ts, src/i18n/locales/en/translation.json, src/jitsi/event-handlers.ts, src/jitsi/init.ts
=> Display appropriate error messages, fix participant signature verification

src/components/WelcomeScreen.tsx
This reverts commit 9ec0d8499117d8a1c6ccd3e53a0a2d969cdf1986.
=> Revert "Revert "Revert "Add web3 gating w/ query param"""

src/components/WelcomeScreen.tsx
This reverts commit 9ec0d8499117d8a1c6ccd3e53a0a2d969cdf1986.
=> Prod Release 2023/05/23

src/components/SubscriptionCTA.tsx, src/components/WelcomeScreen.tsx, src/components/web3/Web3CTA.tsx, src/i18n/locales/en/translation.json
spec: https://docs.google.com/document/d/1boB4S9NQHuUfpj1R6nAHPjf9MPeK3bJpi0tZgmryGIM/edit
=> Update Copy to Match Spec

package-lock.json, package.json
All updates EXCEPT ethers 6.4.0 (still under review)
=> Dpendabot updates as of 2023 05 25

src/components/GlobalStyles.tsx
=> Re-enable text selection

src/components/WelcomeScreen.tsx
=> Fixes merge conflict in #951

src/environment.ts, src/rooms.ts, src/subscriptions.ts
Looks "good" (though needs some devops tweaking on `dev2`)
=> Add`isDevelopment` to aid SKU SDK initialization

package-lock.json, package.json
Looks good on desktop and `dev1
=> Updates as of 2023-06-14

src/components/web3/api.ts
Adding a spam filter using SimpleHash `spam_score`
=> first rendition of spam filter

src/components/web3/api.ts
=> adding console.log debug

.github/workflows/deploy-to-development-premium.yml, .github/workflows/deploy-to-production-premium.yml, .github/workflows/deploy-to-staging-premium.yml
Resolves https://github.com/brave/devops/issues/9881
=> Move GHA to OIDC

src/environment.ts, src/rooms.ts, src/subscriptions.ts
=> Dev2 configuration updates

src/components/web3/api.ts
=> remove debugging console logs, adding Numerical check for spam_score value

src/components/web3/OptionalSettings.tsx, src/components/web3/PermissionTypeSelector.tsx
first mockup of UX change for testing
=> Dsuh 943 bat gating

src/components/web3/OptionalSettings.tsx, src/components/web3/PermissionTypeSelector.tsx
=> change permission name from BAT-gating to balance as per spec sheet

public/branding-config-dev.json, public/labels-english-dev.json
=> tiered branding configuration for labels

package-lock.json, package.json
Addresses: https://github.com/advisories/GHSA-j8xg-fqg3-53r7
=> Address word-wrap audit warning

src/components/web3/OptionalSettings.tsx
Fix for this issue https://github.com/brave/brave-talk/issues/1087
=> Fix for Inability to Deselect Avatar NFT without Selecting Another in Web3 Call

src/components/web3/NonExpandablePanel.tsx, src/components/web3/OptionalSettings.tsx, src/components/web3/PermissionTypeSelector.tsx, src/components/web3/SelectableImageList.tsx, src/components/web3/api.ts, src/components/web3/core.ts, src/hooks/use-web3-call-state.ts, src/i18n/locales/en/translation.json, src/jitsi/conference-page.ts
=> Dsuh avatarurl

src/components/web3/SelectableImageList.tsx
Looks good on desktop. Unable to test on `dev3`...
=> Arithmetic test for spam_score should be >= 80 (not > 80)

src/components/web3/JoinCall.tsx, src/components/web3/OptionalSettings.tsx, src/components/web3/SelectableImageList.tsx, src/components/web3/StartCall.tsx, src/components/web3/api.ts, src/components/web3/core.ts, src/hooks/use-web3-call-state.ts
This provides a fix for an avatar selection bug that was introduced due to the spam filter checkbox, as well as a visual bug resulting from identifying NFTs by their image URL rather than their NFT id.
=> Avatar selection bug fix for Web3 Brave Talk

src/i18n/locales/jp/translation.json
* first mockup on dev2
* remove cluttered talk, add request payload
* change permission name from BAT-gating to balance as per spec sheet
* Renovate/all minor patch (#1062)
* Use renovate for dependency updates (#1054)
1. Disable dependabot for normal dependency updates. Note the dependabot PRs will need to be manually closed, and the "security" dependabot PRs will continue.
2. Use renovateapp instead.
The renovate configuration included here is based on that from ads-serve, and:
a. waits for updates to have been published for 4 days before raising a PR - this both reduces churn and also avoids the 3 day period where npm-published entries can be "unpublished" b. combines all minor and patch updates into a single PR
* removed as *[bot] is not accepted by AWS (#1055)
* Update all non-major …
=> BAT gating translations (#1167)

package-lock.json, package.json, src/components/WelcomeScreen.tsx
=> Remove browser browser requirement

src/jitsi/options.ts, src/jitsi/types.ts
This simply updates the options to force webrtc connections through the Invisv TURN relay.
=> Implement Invisv TURN relay integration

package-lock.json
`npm audit fix` for `follow-redirects`
=> audit: upgrade follow-redirects

src/components/InCall.tsx, src/components/Recordings.tsx, src/jitsi/event-handlers.ts, src/lib.ts, src/recordings-store.ts, src/transcripts.ts
Some small react/css optimization.
=> Transcript support

src/components/LeoPromo.tsx, src/components/WelcomeScreen.tsx, src/i18n/locales/en/translation.json
=> Revert "Revert "Add Leo AI promo""

src/components/InCall.tsx
=> add default transcript

src/components/InCall.tsx
Looks good on `dev1` and `staging`
=> add default transcript (#1403)

src/components/web3/SelectableNFTCollectionList.tsx, src/components/web3/api.ts, src/components/web3/core.ts
=> Add spam_score filtering for NFT collection token-gating

README.md
=> Remove lies from README.md

src/services.ts, src/subscriptions.ts
=> Change development environment to point to premium staging

src/components/web3/api.ts
Closes https://github.com/brave/brave-talk/issues/1236
=> Repeat double crypto pop fix for solana

package-lock.json, package.json
Looks good on desktop, `dev1`, `dev2`, and `dev3`
=> Updated versions of #1486 and #1488

package-lock.json, package.json
Looks good on desktop, `dev1`, `dev2`, and `dev3`
=> Add revised #1486 to main

package-lock.json, package.json, src/components/Button.tsx, webpack.config.js
Resolves https://github.com/brave/brave-talk/issues/1511
=> Remove `backdrop-filter` on buttons + update webpack-dev-server

.github/workflows/codeql-analysis.yml, package-lock.json, package.json, renovate.json
Only renovate updates, most importantly the bump on `cross-spawn`.
Looks good on desktop, `dev1`, `dev2`, `dev3`, and `staging`.
=> Update production from staging

.github/CODEOWNERS, package-lock.json, package.json
and also #1592 because i like it!
=> PR #1588 with npm audit/update

src/i18n/locales/jp/translation.json
=> Update translation.json for JP l10n for Web3 sunset message

src/i18n/locales/en/translation.json, src/transcripts.ts
Resolves https://github.com/brave-intl/brave-talk-server/issues/135
=> Transcript initialization error handling
